export const ADMIN_UI = {
  documentTitle: 'Админка Вкрайности',
  loginTitle: 'Вход в админку',
  loginLabel: 'Логин',
  passwordLabel: 'Пароль',
  loginSubmit: 'Войти',
  loginError: 'Неверный логин или пароль',
  logout: 'Выйти',
  save: 'Сохранить',
  saving: 'Сохраняем…',
  saved: 'Черновик сохранён — на сайт попадёт после «Опубликовать»',
  saveError: 'Не удалось сохранить',
  conflict: 'Черновик обновили в другом окне. Перезагрузите страницу.',
  loadError: 'Не удалось загрузить тур',
  listTitle: 'Туры',
  listDescription: 'Выберите сезон или индивидуальные туры.',
  toursNav: 'Туры',
  backToTours: 'К сезонам',
  backToSeasonTours: 'К турам сезона',
  searchTours: 'Найти тур',
  tourVisibilityFilter: 'На сайте или скрыт',
  tourVisibility: {
    all: 'Все',
    on_site: 'На сайте',
    hidden: 'Скрыт',
  },
  individualTours: 'Индивидуальные туры',
  individualTitle: 'Индивидуальные туры',
  individualDescription: 'Отдельная категория — логика будет другой, чем у сезонных туров.',
  individualEmpty: 'Пока нет индивидуальных туров',
  individualEmptyHint: 'Этот раздел подключим отдельно, без сезонной сетки.',
  seasonToursDescription: 'Карточки сезона. На сайте — после публикации, скрытые не показываем гостю.',
  tourStatus: {
    draft: 'Черновик',
    in_development: 'В работе',
    active: 'На сайте',
    hidden: 'Скрыт',
  },
  collapseSeason: 'Свернуть сезон',
  expandSeason: 'Развернуть сезон',
  usersNav: 'Люди',
  usersTitle: 'Пользователи админки',
  usersDescription: 'Кто может править черновики и публиковать.',
  usersEmpty: 'Пока никого нет',
  usersEmptyHint: 'Добавьте первого редактора или админа.',
  roleLabel: 'Роль',
  roleAdmin: 'Админ',
  roleEditor: 'Редактор',
  addUser: 'Добавить',
  addUserTitle: 'Новый пользователь',
  deleteUser: 'Удалить пользователя',
  deleteUserTitle: 'Удалить пользователя',
  deleteUserBody: 'Учётку нельзя восстановить.',
  deleteUserConfirm: 'Удалить учётку',
  cancel: 'Отмена',
  newPasswordLabel: 'Новый пароль',
  changePassword: 'Сменить пароль',
  userCreated: 'Пользователь добавлен',
  passwordChanged: 'Пароль обновлён',
  userError: 'Не удалось сохранить пользователя',
  loginTaken: 'Такой логин уже есть',
  lastAdmin: 'Нельзя убрать последнего админа',
  cannotDeleteSelf: 'Нельзя удалить свою учётку',
  publish: 'Опубликовать',
  publishing: 'Публикуем…',
  published: 'Опубликовано — localhost подтянет с cms-dev',
  publishError: 'Не удалось опубликовать',
  publishNeedSave: 'Сначала сохраните черновик',
  publishBlockers: {
    cover_required: 'Нужна обложка карточки',
    pool_not_empty: 'В пуле остались кадры вне сетки',
    bento_empty_slots: 'В сетке есть пустые ячейки',
    included_icon_required: 'У пунктов с текстом нужна иконка',
  },
  emptyList: 'Туры не найдены',
  emptyListHint: 'Создайте первый тур — он появится в списке сезона.',
  emptySearch: 'По запросу ничего нет',
  addTour: 'Добавить тур',
  createTourTitle: 'Новый тур',
  createTourSeason: 'Сезон',
  tourNameLabel: 'Название тура',
  tourSlugLabel: 'Адрес страницы',
  tourSlugHint: 'Латиница, цифры и дефис — так тур откроется на сайте',
  tourUrlPreview: 'Адрес на сайте',
  regenerateSlug: 'Собрать из названия',
  createTourSubmit: 'Создать',
  createTourCancel: 'Отмена',
  createTourError: 'Не удалось создать тур',
  slugTaken: 'Такой адрес уже занят',
  invalidSlug: 'Адрес: только латиница, цифры и дефис',
  aboutHeading: 'О поездке',
  prefaceLabel: 'Фон блока',
  leadLabel: 'Жирный лид',
  descriptionLabel: 'Основной текст',
  asideLabel: 'Правая колонка',
  includedHeading: 'Что включено в стоимость участия',
  includedTextLabel: 'Подпись пункта',
  includedIconLabel: 'Иконка',
  includedIconUnset: 'Выбрать иконку',
  includedIconPickerTitle: 'Иконка пункта',
  includedPreview: 'Как на сайте',
  addIncluded: 'Добавить пункт',
  removeItem: 'Удалить',
  moveUp: 'Выше',
  moveDown: 'Ниже',
  programHeading: 'Программа поездки',
  timeLabel: 'Время',
  stepLabel: 'Шаг',
  addStep: 'Добавить шаг',
  notesHeading: 'Примечания под программой',
  addNote: 'Добавить примечание',
  noteLabel: 'Примечание',
  unsaved: 'Есть несохранённые правки',
  loading: 'Загрузка…',
  coverLabel: 'Обложка карточки',
  galleryHeading: 'Галерея bento',
  sectionNav: {
    catalog: 'Карточка',
    about: 'О поездке',
    included: 'Включено',
    program: 'Программа',
    gallery: 'Галерея',
  },
  catalogHeading: 'Карточка и цена',
  subtitleLabel: 'Подзаголовок',
  heroPhraseLabel: 'Фраза в hero',
  durationLabel: 'Длительность',
  difficultyLabel: 'Сложность',
  difficultyDisplayLabel: 'Подпись сложности (необязательно)',
  audienceLabel: 'Аудитория на карточке (необязательно)',
  priceLabel: 'Цена',
  pricePreviousLabel: 'Старая цена (необязательно)',
  priceFootnoteLabel: 'Сноска к цене (необязательно)',
  seoDescriptionLabel: 'SEO-описание (необязательно)',
  poolLabel: 'Пул галереи',
  poolEmpty: 'Загрузите кадры — обложка и предисловие в сетку не кладутся',
  usedInGrid: 'В сетке',
  unusedInGrid: 'Свободен',
  addPhoto: 'Добавить фото',
  dropMedia: 'Перетащите фото или видео, можно несколько. Или нажмите, чтобы выбрать.',
  dropOneMedia: 'Перетащите фото или видео. Или нажмите, чтобы выбрать.',
  addToSlot: 'Добавить в ячейку',
  pickUnusedTitle: 'Свободные кадры',
  pickUnusedEmpty: 'Свободных кадров нет — загрузите их в пул справа',
  changePhoto: 'Сменить фото',
  poolAltPlaceholder: 'Подпись',
  addBlockHint: 'Выберите схему — блок добавится в конец сетки',
  videoBadge: 'Видео',
  focalPoint: 'Точка кадра',
  coverCropHeading: 'Кадрирование обложки',
  coverCropCard: 'Карточка',
  coverCropHero: 'Hero, до большого экрана',
  coverCropHeroLg: 'Hero, большой экран',
  coverCropHint: 'Перетащите точку — так кадр встанет на сайте',
  emptySlot: 'Пустая ячейка',
  changeBlockType: 'Сменить схему блока',
  collapseGallery: 'Свернуть пул',
  expandGallery: 'Показать пул',
  deleteAsset: 'Удалить кадр',
  confirmDeleteAsset: 'Удалить этот кадр с cms-dev? Файл нельзя вернуть.',
  dragBlock: 'Переставить блок',
  closePicker: 'Закрыть',
  uploadStill: 'Кадр (webp, jpg, png)',
  uploadVideo: 'Видео к кадру (необязательно)',
  uploadAlt: 'Подпись кадра',
  uploadSubmit: 'Загрузить на cms-dev',
  uploading: 'Загружаем…',
  uploadError: 'Не удалось загрузить файл',
  deleteError: 'Не удалось удалить кадр',
  deleteInUse: 'Кадр занят обложкой, фоном или сеткой',
  blockTypes: {
    'bento-left': 'Высокий слева',
    'bento-right': 'Высокий справа',
    'bento-center-top': 'Широкий сверху',
    'bento-center-bottom': 'Широкий снизу',
    'bento-four': 'Четыре квадрата',
    'bento-single': 'Один на всю ширину',
    'bento-wide-square': 'Широкий квадрат',
    'bento-vert': 'Два высоких',
  },
  crmNav: 'Заявки',
  crmTitle: 'Заявки',
  crmDescription: 'Лиды, потенциальные гости и контакты.',
  crmAdd: 'Добавить',
  crmAddTitle: 'Новая карточка',
  crmKindLead: 'Заявка',
  crmKindContact: 'Контакт',
  crmSearch: 'Найти',
  crmEmptyLeads: 'Заявок нет',
  crmEmptyLeadsHint: 'Добавьте заявку или дождитесь формы с сайта.',
  crmEmptyPotential: 'Потенциальных гостей нет',
  crmEmptyContacts: 'Контактов нет',
  crmEmptyContactsHint: 'Поставщики, турбазы, водители — в папках контактов.',
  crmViews: {
    leads: 'Лиды',
    potential: 'Потенциальные',
    contacts: 'Контакты',
  },
  crmName: 'Имя',
  crmPhone: 'Телефон',
  crmMessenger: 'Как писать',
  crmHandle: 'Ник в мессенджере',
  crmNote: 'Заметка',
  crmFolder: 'Папка',
  crmFolderNone: 'Без папки',
  crmFolderCustom: 'Новая папка',
  crmTour: 'Тур',
  crmDate: 'Дата выезда',
  crmComment: 'Комментарий',
  crmPauseReason: 'Почему ждём / отказ',
  crmNextStep: 'Следующий шаг',
  crmNextStepAt: 'Когда',
  crmPaid: 'Оплата внесена',
  crmDoubts: 'Сомневается',
  crmStatus: 'Статус',
  crmDeals: 'Попытки записи',
  crmAddDeal: 'Ещё тур',
  crmCalled: 'Позвонил',
  crmWrote: 'Написал',
  crmOpenChat: 'Написать',
  crmCall: 'Позвонить',
  crmSavePerson: 'Сохранить карточку',
  crmBackToList: 'К списку',
  crmError: 'Не удалось сохранить заявку',
  crmConflict: 'Список обновили в другом окне. Обновите страницу.',
  crmMessengers: {
    telegram: 'Telegram',
    whatsapp: 'WhatsApp',
    max: 'Max',
    phone: 'Телефон',
  },
  crmStatuses: {
    new: 'Новая',
    in_progress: 'В работе',
    booked: 'Записали',
    declined: 'Отказ',
    no_answer: 'Нет ответа',
  },
  crmFolders: {
    suppliers: 'Поставщики',
    tour_bases: 'Турбазы',
    captains: 'Капитаны',
    drivers: 'Водители',
    other: 'Другое',
  },
  seasons: {
    winter: 'Зима',
    spring: 'Весна',
    summer: 'Лето',
    fall: 'Осень',
  },
  iconLabels: {
    bed: 'Ночёвка',
    binoculars: 'Наблюдение',
    'book-open': 'Программа',
    'chalkboard-user': 'Инструктаж',
    check: 'Включено',
    dog: 'Собаки',
    heart: 'Забота',
    'helmet-safety': 'Снаряжение',
    'hot-tub-person': 'Баня',
    'mug-hot': 'Горячее питьё',
    'mug-saucer': 'Кофе',
    paw: 'Животные',
    'person-hiking': 'Поход',
    'person-snowboarding': 'Сноуборд',
    plane: 'Перелёт',
    socks: 'Гамаши',
    ticket: 'Билет',
    truck: 'Транспорт',
    'user-tie': 'Гид',
    utensils: 'Еда',
    'van-shuttle': 'Трансфер',
    water: 'Вода',
    wind: 'Ветер',
  } as Record<string, string>,
} as const;
