export const ADMIN_UI = {
  documentTitle: 'Админка Вкрайности',
  skipToContent: 'К содержанию',
  editorSections: 'Разделы карточки',
  primaryNav: 'Разделы админки',
  collapseNav: 'Свернуть меню',
  expandNav: 'Развернуть меню',
  moreNav: 'Ещё',
  closeOverlay: 'Закрыть',
  quickAdd: 'Создать',
  soon: 'скоро',
  retry: 'Повторить',
  pageLoadError: 'Не удалось загрузить',
  permissionDeniedTitle: 'Нет доступа',
  usersPermissionDenied: 'Только администратор может управлять пользователями.',
  returnToDashboard: 'К началу',
  undo: 'Отменить',
  toastDismiss: 'Скрыть',
  listReordered: 'Порядок обновлён',
  listItemRemoved: 'Пункт удалён',
  scheduleMoved: 'Выезд перенесён',
  showProblems: 'Показать проблемы',
  openEditorActions: 'Открыть действия редактора',
  readinessReady: 'готово',
  blockersOne: '1 блокер',
  blockersFew: 'блокера',
  blockersMany: 'блокеров',
  emptySearchReset: 'Сбросить фильтры',
  columnKind: 'Тип',
  columnRole: 'Роль',
  columnAccess: 'Доступ',
  fullAccess: 'Полный доступ',
  usersDraftOnly: 'Только черновики',
  tourListView: 'Вид списка',
  tourViewCards: 'Карточки',
  tourViewList: 'Список',
  inboxTablist: 'Тип очереди',
  inboxTabTours: 'Туры',
  inboxTabSchedule: 'Расписание',
  inboxTabDepartures: 'Выезды',
  inboxReadyFilter: 'Готовность к публикации',
  inboxReadyAll: 'Все статусы',
  inboxReadyOnly: 'Готово',
  inboxBlockersOnly: 'С блокерами',
  inboxAuthorFilter: 'Кто сделал правку',
  inboxAuthorAll: 'Все авторы',
  inboxAuthorUnknown: 'Не указан',
  inboxSearch: 'Найти в очереди',
  inboxSort: 'Сортировка',
  inboxSortNewest: 'Сначала новые',
  inboxSortOldest: 'Сначала старые',
  inboxStatTours: 'Ждут публикации туры',
  inboxStatDepartures: 'Ждут публикации даты',
  inboxStatBlockers: 'Есть блокеры, требуют внимания',
  inboxColumnType: 'Тип',
  inboxColumnName: 'Название / дата',
  inboxColumnStatus: 'Статус',
  inboxColumnAuthor: 'Отправил',
  inboxColumnSent: 'Отправлено',
  inboxColumnReady: 'Готово к публикации',
  inboxColumnActions: 'Действия',
  inboxView: 'Просмотреть',
  inboxPublishOne: 'Опубликовать',
  inboxReadyYes: 'Готов',
  inboxHasBlockers: 'Есть блокеры',
  relativeJustNow: 'только что',
  relativeMinutesAgo: 'мин назад',
  relativeHoursAgo: 'ч назад',
  scheduleOverflow: 'ещё',
  scheduleOverflowDeparturesOne: 'выезд',
  scheduleOverflowDeparturesFew: 'выезда',
  scheduleOverflowDeparturesMany: 'выездов',
  scheduleDepartureCountOne: 'выезд',
  scheduleDepartureCountFew: 'выезда',
  scheduleDepartureCountMany: 'выездов',
  scheduleHiddenFromGuest: 'Скрыт',
  scheduleShownDepartures: 'Показано выездов',
  scheduleGoToDay: 'Перейти к дню',
  scheduleFilter: 'Фильтр',
  scheduleStatusLegend: 'Статусы выездов',
  scheduleAddDeparture: 'Добавить выезд',
  scheduleModes: 'Вид календаря',
  loginTitle: 'Вход в админку',
  logoAlt: 'Вкрайности',
  loginLabel: 'Логин',
  passwordLabel: 'Пароль',
  loginSubmit: 'Войти',
  loginError: 'Неверный логин или пароль',
  logout: 'Выйти',
  save: 'Сохранить',
  saving: 'Сохраняем…',
  saved: 'Черновик сохранён — на сайт попадёт после «Опубликовать»',
  autosaved: 'Сохранено',
  unpublishedChanges: 'Есть неопубликованные изменения',
  saveError: 'Не удалось сохранить',
  conflict: 'Черновик обновили в другом окне. Перезагрузите страницу.',
  loadError: 'Не удалось загрузить тур',
  dashboardNav: 'Сегодня',
  dashboardTitle: 'Сегодня',
  dashboardDescription: 'Что требует внимания и что происходит в выездах.',
  dashboardAttention: 'Требует внимания',
  dashboardAttentionEmpty: 'Сейчас нет срочных задач',
  dashboardPublication: 'Публикация',
  dashboardPublicationEmpty: 'Очередь пуста',
  dashboardReturned: 'Возвращено на доработку',
  dashboardOpenPublication: 'Открыть публикацию',
  dashboardFixReadiness: 'Исправить готовность',
  dashboardQueueAttention: 'Ожидает публикации',
  dashboardMetricOnSite: 'На сайте',
  dashboardMetricAttention: 'Требуют внимания',
  dashboardMetricPublicationQueue: 'В очереди публикации',
  dashboardQuickActions: 'Быстрые действия',
  dashboardOpenCatalog: 'Каталог туров',
  dashboardOpenInbox: 'Очередь публикации',
  dashboardSeats: 'Мест',
  dashboardOpenCalendar: 'Открыть календарь',
  dashboardUpcomingEmptyDescription: 'Запланируйте следующий выезд в календаре.',
  dashboardMyWork: 'Моя работа',
  dashboardActivityPlaceholderTitle: 'История активности',
  dashboardActivityPlaceholderDescription: 'Детальная история появится после подключения журнала действий.',
  dashboardMoreAttention: 'Показать остальные задачи',
  dashboardCurrentQuiet: 'Сейчас нет активных выездов',
  dashboardNextDeparture: 'Следующий выезд',
  dashboardReadinessIncomplete: 'Не готовы разделы',
  dashboardRelativeToday: 'Сегодня',
  dashboardRelativeTomorrow: 'Завтра',
  dashboardRelativeDaysPrefix: 'Через',
  dashboardRelativeDaysSuffix: 'дн.',
  dashboardSeverity: {
    critical: 'Критично',
    prepublication: 'Перед публикацией',
    later: 'Можно позже',
  },
  onSiteCountOutOf: 'из',
  onSiteCountSuffix: 'на сайте',
  departureGuestWillSee: 'Гость увидит',
  departureGuestWontSee: 'Гость не увидит',
  tourOpenOnSite: 'Открыть на сайте',
  tourPreviewAsGuest: 'Как увидит гость',
  cancelledThisWeekOne: '1 отменён на этой неделе',
  cancelledThisWeekMany: 'отменены на этой неделе',
  listTitle: 'Туры',
  listDescription: 'Сезон по календарю. Другой сезон — переключите сверху.',
  seasonSwitcher: 'Сезоны',
  homeNearest: 'Ближайшие',
  homeCurrent: 'Текущие',
  homeNearestEmpty: 'Ближайших выездов нет',
  homeCurrentEmpty: 'Сейчас никто не в поездке',
  toursNav: 'Туры',
  scheduleNav: 'Календарь',
  scheduleTitle: 'Календарь выездов',
  scheduleModeDay: 'День',
  scheduleModeWeek: 'Неделя',
  scheduleModeMonth: 'Месяц',
  scheduleWeekLayout: 'Вид недели',
  scheduleWeekList: 'Список недели',
  scheduleWeekSplit: 'Неделя с панелью',
  scheduleSelectDay: 'Выбрать день',
  scheduleWeekEmpty: 'На этой неделе выездов нет.',
  scheduleDayEmpty: 'На эту дату выездов нет.',
  scheduleSeatsTotal: 'мест всего',
  schedulePrev: 'Назад',
  scheduleNext: 'Вперёд',
  scheduleToday: 'Сегодня',
  scheduleEmptyCell: 'Добавить выезд',
  scheduleWizardTitle: 'Новый выезд',
  schedulePickTour: 'Тур',
  schedulePickDate: 'Дата старта',
  scheduleStaffSkip: 'Гид и водитель — для дальнейшей разработки',
  scheduleSeats: 'Мест',
  scheduleWizardNext: 'Далее',
  scheduleWizardSubmit: 'Создать выезд',
  scheduleAddFromTour: 'Добавить выезд',
  scheduleAdd: 'Создать выезд',
  scheduleAddOnDate: 'Добавить тур на эту дату',
  scheduleChipListTitle: 'Выезды в этот день',
  scheduleEditorTitle: 'Выезд',
  scheduleDelete: 'Удалить выезд',
  scheduleDeleteTitle: 'Удалить выезд',
  scheduleDeleteBody: 'Выезд исчезнет из календаря. На сайте пропадёт после публикации расписания.',
  scheduleDeletePublishedBody:
    'Эта дата уже на сайте. Удалить её нельзя — отмените выезд и опубликуйте расписание.',
  scheduleDeleteConfirm: 'Удалить',
  scheduleDeleted: 'Выезд удалён',
  scheduleDeleteError: 'Не удалось удалить выезд',
  scheduleNoToursForDate: 'Все туры на сайте уже стоят на эту дату.',
  scheduleNoOnSiteTours: 'В этом сезоне нет туров на сайте.',
  scheduleCrossSeasonTitle: 'Тур другого сезона',
  scheduleCrossSeasonBody:
    '«{tour}» относится к сезону «{tourSeason}», а выбранная дата — к «{calendarSeason}». На общем календаре сайта выезд всё равно появится; в каталоге другого сезона тур не покажется — только на странице тура. Добавить выезд?',
  scheduleCrossSeasonConfirm: 'Всё равно добавить',
  departureStatusMenu: 'Сменить статус выезда',
  scheduleLoadError: 'Не удалось загрузить календарь',
  scheduleSaveError: 'Не удалось сохранить выезд',
  scheduleTourNotReady: 'Сначала завершите подготовку тура, затем создайте выезд.',
  scheduleNoPublishableDepartures: 'Нет выездов, готовых к публикации.',
  scheduleDraftUpToDate: 'Расписание актуально',
  scheduleDraftChangesOne: '1 неопубликованное изменение',
  scheduleDraftChangesMany: 'неопубликованных изменений',
  scheduleNearestDepartures: 'Ближайшие выезды',
  scheduleNearestDeparturesEmpty: 'В ближайший период выездов нет',
  scheduleOpenAllDepartures: 'Открыть все выезды',
  scheduleNewDepartureMaster: 'Мастер нового выезда',
  scheduleDraftDepartures: 'Черновики выездов',
  scheduleDraftDeparturesEmpty: 'Черновиков выездов нет',
  schedulePlaceholderUnavailable: 'Подключим позже',
  scheduleSearchLabel: 'Поиск по турам, людям, заявкам',
  scheduleNotifications: 'Уведомления',
  scheduleAccountRoleAdmin: 'Администратор',
  scheduleAccountRoleEditor: 'Редактор',
  scheduleFiltersPlaceholder: 'Фильтры',
  scheduleMoreActions: 'Дополнительные действия расписания',
  scheduleTimezone: 'Азия / Владивосток · GMT+10',
  scheduleStatus: 'Статус',
  scheduleMoveHint: 'Перенос: перетащите чип или смените дату в карточке выезда.',
  cancelDepartureTitle: 'Отменить выезд',
  cancelDepartureConfirm: 'Отменить',
  cancelDepartureReason: 'Причина отмены',
  cancelDepartureComment: 'Комментарий',
  cancelDepartureReasons: {
    low_attendance: 'Недостаточно участников',
    weather: 'Погода',
    transport: 'Транспорт / оборудование',
    staff: 'Гид / команда',
    access: 'Ограничения доступа / территории',
    force_majeure: 'Форс-мажор',
    organizer: 'Решение организатора',
    other: 'Другое',
  },
  scheduleWeekdays: ['Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб', 'Вс'],
  departureStatus: {
    planned: 'Запланирован',
    open: 'Набор открыт',
    full: 'Почти заполнен',
    cancelled: 'Отменён',
    completed: 'Завершён',
  },
  backToTours: 'К каталогу туров',
  backToSeasonTours: 'К турам сезона',
  tourMenu: 'Действия тура',
  tourOpenEditor: 'Открыть карточку',
  tourHideFromSite: 'Скрыть с сайта',
  tourHideQueuedAction: 'Поставить скрытие в публикации',
  tourShowOnSite: 'Вернуть на сайт',
  tourHiddenOnSite: 'Тур скрыт с сайта',
  tourShownOnSite: 'Тур снова на сайте',
  tourHiddenQueued: 'Скрытие в очереди публикации — гость увидит после выпуска',
  tourShownQueued: 'Возврат на сайт в очереди публикации — гость увидит после выпуска',
  tourGuestVisibilityError: 'Не удалось изменить видимость на сайте',
  tourNearest: 'Ближайший выезд',
  tourNearestNone: 'Ближайшего выезда нет',
  searchTours: 'Найти тур',
  tourVisibilityFilter: 'Видимость на сайте',
  tourVisibility: {
    all: 'Все',
    on_site: 'На сайте',
    in_development: 'В работе',
    hidden: 'Скрыт',
    draft: 'Черновик',
  },
  tourLiveVisibility: {
    draft: 'Черновик',
    on_site: 'На сайте',
    will_hide: 'Будет скрыт',
    hidden: 'Скрыт',
    will_show: 'Будет на сайте',
    in_development: 'В работе',
  },
  tourOperationalStatus: {
    on_site: 'На сайте',
    hidden: 'Скрыт',
    ready: 'Готов к публикации',
    blocked: 'Есть блокеры',
  },
  individualTours: 'Индивидуальные туры',
  individualTitle: 'Индивидуальные туры',
  individualDescription: 'Отдельная категория — логика будет другой, чем у сезонных туров.',
  individualEmpty: 'Пока нет индивидуальных туров',
  individualEmptyHint: 'Этот раздел подключим отдельно, без сезонной сетки.',
  seasonToursDescription: 'Карточки сезона. На сайте — после публикации, скрытые не показываем гостю.',
  tourStatus: {
    draft: 'Черновик',
    in_development: 'В работе',
    active: 'На сайте',
    hidden: 'Скрыт',
  },
  collapseSeason: 'Свернуть сезон',
  expandSeason: 'Развернуть сезон',
  usersNav: 'Люди',
  usersTitle: 'Пользователи админки',
  usersDescription: 'Кто может править черновики и публиковать.',
  usersEmpty: 'Пока никого нет',
  usersEmptyHint: 'Добавьте первого редактора или админа.',
  roleLabel: 'Роль',
  roleAdmin: 'Админ',
  roleEditor: 'Редактор',
  publishToursFlag: 'Может публиковать туры',
  publishScheduleFlag: 'Может публиковать расписание',
  usersRoleConfirm: 'Сменить роль этого пользователя? Это сразу меняет доступ в админке.',
  usersPublishFlagConfirm: 'Изменить право публикации? Это сразу меняет, что человек может выпускать на сайт.',
  usersAccessConfirm: 'Изменить доступ',
  inboxNav: 'Публикации',
  inboxTitle: 'Публикации',
  inboxDescription: 'Очередь публикации туров и выездов.',
  inboxStats: 'Сводка очереди',
  inboxEmpty: 'Сейчас нечего публиковать',
  inboxEmptyHint: 'Сохраните черновик тура или дату выезда — они появятся здесь.',
  inboxSubmit: 'Отправить на публикацию',
  inboxSubmitAll: 'Отправить всё на публикацию',
  inboxSubmitSelected: 'Отправить выбранное',
  inboxPublishAll: 'Опубликовать всё',
  inboxPublishSelected: 'Опубликовать выбранное',
  inboxPublishing: 'Публикуем…',
  inboxPublished: 'Опубликовано',
  inboxPublishError: 'Не удалось опубликовать',
  inboxSelectItem: 'Выбрать',
  inboxSubmitting: 'Отправляем…',
  inboxSubmitted: 'Отправлено в очередь',
  inboxSubmitError: 'Не удалось отправить на публикацию',
  inboxTourItem: 'Тур',
  inboxDepartureItem: 'Выезд',
  inboxAuthor: 'Автор',
  inboxChanged: 'Изменено',
  inboxSummaryNewTour: 'Новый тур',
  inboxSummaryTourDraft: 'Изменения в черновике',
  inboxSummaryNewDeparture: 'Новый выезд',
  inboxSummaryDepartureDraft: 'Изменения выезда',
  inboxDiffTitle: 'Что изменится на сайте',
  inboxDiffEmpty: 'Нет полей для сравнения — это новая сущность.',
  inboxDiffPrice: 'Цена',
  inboxDiffSeason: 'Сезон',
  inboxDiffDate: 'Дата',
  inboxReturn: 'Вернуть на доработку',
  inboxReturnShort: 'Вернуть',
  inboxReturnReason: 'Почему возвращаем',
  inboxReturnError: 'Не удалось вернуть',
  inboxReturned: 'Возвращено на доработку',
  publishSchedule: 'Опубликовать расписание',
  addUser: 'Добавить',
  addUserTitle: 'Новый пользователь',
  deleteUser: 'Удалить пользователя',
  deleteUserTitle: 'Удалить пользователя',
  deleteUserBody: 'Учётку нельзя восстановить.',
  deleteUserConfirm: 'Удалить учётку',
  cancel: 'Отмена',
  newPasswordLabel: 'Новый пароль',
  changePassword: 'Сменить пароль',
  userCreated: 'Пользователь добавлен',
  passwordChanged: 'Пароль обновлён',
  userError: 'Не удалось сохранить пользователя',
  loginTaken: 'Такой логин уже есть',
  lastAdmin: 'Нельзя убрать последнего админа',
  cannotDeleteSelf: 'Нельзя удалить свою учётку',
  publish: 'Опубликовать',
  publishing: 'Публикуем…',
  published: 'Опубликовано — localhost подтянет с cms-dev',
  publishError: 'Не удалось опубликовать',
  publishHideConfirmTitle: 'Удалить будущие выезды?',
  publishHideConfirmBody:
    'После выпуска скрытого тура будущие несостоявшиеся выезды исчезнут из календаря. Прошедшие и завершённые останутся. Если вернуть тур на сайт, даты сами не появятся — их нужно создать заново.',
  publishHideConfirm: 'Да, удалить выезды',
  publishHideHasLeads: 'Нельзя скрыть тур: на будущие даты есть заявки.',
  publishNeedSave: 'Сначала сохраните черновик',
  publishAfterSave: 'Сначала дождитесь сохранения черновика.',
  publishBlockers: {
    cover_required: 'Нужна обложка карточки',
    bento_empty_slots: 'В сетке есть пустые ячейки',
    included_icon_required: 'У пунктов с текстом нужна иконка',
    tour_not_ready: 'Заполните все разделы — карточка, о поездке, включено, программа и галерея',
  },
  requiredForPublish: 'Нужно для публикации',
  tabHasBlocker: 'есть блокер',
  catalogExtrasHeading: 'Дополнительно для сайта',
  aboutCoverHeading: 'Обложка',
  aboutTextHeading: 'Текст о поездке',
  aboutColumnsHint: 'Как на сайте: жирный лид и две колонки текста.',
  identityHeading: 'Название и адрес',
  editorRailReadiness: 'Готовность',
  editorReadinessCard: 'Готовность карточки',
  editorRailPublication: 'Публикация',
  editorNoBlockers: 'Блокеров нет',
  includedEmpty: 'Пунктов пока нет',
  includedEmptyHint: 'Добавьте, что входит в стоимость.',
  programEmpty: 'Шагов пока нет',
  programEmptyHint: 'Добавьте программу поездки.',
  addBlock: 'Добавить блок',
  dragItem: 'Переставить',
  saveOrder: 'Сохранить порядок',
  emptyList: 'Туры не найдены',
  emptyListHint: 'Создайте первый тур — он появится в списке сезона.',
  emptySearch: 'По запросу ничего нет',
  addTour: 'Добавить тур',
  createTourTitle: 'Новый тур',
  createTourSeason: 'Сезон',
  tourNameLabel: 'Название тура',
  tourGuestStatusLabel: 'Видимость для гостя',
  tourGuestStatusHint:
    'Пока тур не опубликован, гость его не видит. Здесь — каким он станет на сайте после «Опубликовать». «Скрыт» и «В работе» сохраняются как есть.',
  tourSlugLabel: 'Адрес страницы',
  tourSlugHint: 'Латиница, цифры и дефис — так тур откроется на сайте',
  tourUrlPreview: 'Адрес на сайте',
  regenerateSlug: 'Собрать из названия',
  createTourSubmit: 'Создать',
  createTourCancel: 'Отмена',
  createTourError: 'Не удалось создать тур',
  slugTaken: 'Такой адрес уже занят',
  invalidSlug: 'Адрес: только латиница, цифры и дефис',
  aboutHeading: 'О поездке',
  prefaceLabel: 'Фон блока',
  leadLabel: 'Жирный лид',
  descriptionLabel: 'Левая колонка',
  asideLabel: 'Правая колонка',
  includedHeading: 'Что включено в стоимость участия',
  includedTextLabel: 'Подпись пункта',
  includedIconLabel: 'Иконка',
  includedIconUnset: 'Выбрать иконку',
  includedIconPickerTitle: 'Иконка пункта',
  includedPreview: 'Как на сайте',
  addIncluded: 'Добавить пункт',
  removeItem: 'Удалить',
  moveUp: 'Выше',
  moveDown: 'Ниже',
  programHeading: 'Программа поездки',
  programDay: (day: number) => `День ${day}`,
  programOverflow: 'Есть пункты за пределами выбранной длительности — они сохранены и требуют внимания.',
  timeLabel: 'Время',
  stepLabel: 'Шаг',
  addStep: 'Добавить шаг',
  notesHeading: 'Примечания под программой',
  notesEmpty: 'Примечаний пока нет',
  notesEmptyHint: 'Добавьте уточнение, которое увидит гость под программой.',
  addNote: 'Добавить примечание',
  noteLabel: 'Примечание',
  unsaved: 'Есть несохранённые правки',
  loading: 'Загрузка…',
  coverLabel: 'Обложка карточки',
  galleryHeading: 'Галерея bento',
  sectionNav: {
    catalog: 'Карточка',
    about: 'О поездке',
    included: 'Включено',
    program: 'Программа',
    gallery: 'Галерея',
  },
  catalogHeading: 'Карточка и цена',
  subtitleLabel: 'Подзаголовок',
  heroPhraseLabel: 'Фраза в hero',
  durationLabel: 'Длительность',
  durationUnset: 'Выберите длительность',
  difficultyLabel: 'Сложность',
  difficultyDisplayLabel: 'Подпись сложности (необязательно)',
  audienceLabel: 'Аудитория на карточке (необязательно)',
  priceLabel: 'Цена',
  pricePreviousLabel: 'Старая цена (необязательно)',
  priceFootnoteLabel: 'Сноска к цене (необязательно)',
  seoDescriptionLabel: 'SEO-описание (необязательно)',
  poolLabel: 'Пул галереи',
  poolEmpty: 'Загрузите кадры — обложка и предисловие в сетку не кладутся',
  usedInGrid: 'В сетке',
  unusedInGrid: 'Свободен',
  addPhoto: 'Добавить фото',
  dropMedia: 'Перетащите фото или видео, можно несколько. Или нажмите, чтобы выбрать.',
  dropOneMedia: 'Перетащите фото или видео. Или нажмите, чтобы выбрать.',
  addToSlot: 'Добавить в ячейку',
  addMedia: 'Добавить медиа',
  addToBento: 'Добавить в bento',
  deleteFromPool: 'Удалить из пула',
  poolAssetActions: 'Действия с файлом',
  selectBentoSlot: 'Выберите свободную ячейку',
  noFreeBentoSlot: 'Свободных ячеек нет — сначала добавьте схему',
  pickUnusedTitle: 'Свободные кадры',
  pickUnusedEmpty: 'Свободных кадров нет — загрузите их в пул справа',
  changePhoto: 'Сменить фото',
  changeBackground: 'Сменить фон',
  poolAltPlaceholder: 'Подпись',
  addBlockHint: 'Выберите схему — блок добавится в конец сетки',
  videoBadge: 'Видео',
  focalPoint: 'Точка кадра',
  coverCropHeading: 'Кадрирование обложки',
  coverCropCard: 'Карточка тура',
  coverCropHero: 'Hero вертикальный',
  coverCropHeroLg: 'Hero большой',
  coverCropHint: 'Перетащите точку — так кадр встанет на сайте',
  emptySlot: 'Пустая ячейка',
  changeBlockType: 'Сменить схему блока',
  collapseGallery: 'Свернуть пул',
  expandGallery: 'Показать пул',
  deleteAsset: 'Удалить кадр',
  confirmDeleteAsset: 'Удалить этот кадр с cms-dev? Файл нельзя вернуть.',
  dragBlock: 'Переставить блок',
  closePicker: 'Закрыть',
  uploadStill: 'Кадр (webp, jpg, png)',
  uploadVideo: 'Видео к кадру (необязательно)',
  uploadAlt: 'Подпись кадра',
  uploadSubmit: 'Загрузить на cms-dev',
  uploading: 'Загружаем…',
  uploadProgress: (completed: number, total: number) => `Загружаем медиа: ${completed} из ${total}`,
  uploadError: 'Не удалось загрузить файл',
  retryUpload: 'Повторить неудачные',
  failedUploads: (count: number) => `Не загрузилось: ${count}`,
  deleteError: 'Не удалось удалить кадр',
  deleteInUse: 'Кадр занят обложкой, фоном или сеткой',
  blockTypes: {
    'bento-left': 'Высокий слева',
    'bento-right': 'Высокий справа',
    'bento-center-top': 'Широкий сверху',
    'bento-center-bottom': 'Широкий снизу',
    'bento-four': 'Четыре квадрата',
    'bento-single': 'Один на всю ширину',
    'bento-wide-square': 'Широкий квадрат',
    'bento-vert': 'Два высоких',
  },
  crmNav: 'Заявки',
  crmTitle: 'Заявки',
  crmDescription: 'Лиды, потенциальные гости и контакты.',
  crmAdd: 'Добавить',
  crmAddTitle: 'Новая карточка',
  crmKindLead: 'Заявка',
  crmKindContact: 'Контакт',
  crmSearch: 'Найти',
  crmEmptyLeads: 'Заявок нет',
  crmEmptyLeadsHint: 'Добавьте заявку или дождитесь формы с сайта.',
  crmEmptyPotential: 'Потенциальных гостей нет',
  crmEmptyContacts: 'Контактов нет',
  crmEmptyContactsHint: 'Поставщики, турбазы, водители — в папках контактов.',
  crmViews: {
    leads: 'Лиды',
    potential: 'Потенциальные',
    contacts: 'Контакты',
  },
  crmName: 'Имя',
  crmPhone: 'Телефон',
  crmMessenger: 'Как писать',
  crmHandle: 'Ник в мессенджере',
  crmNote: 'Заметка',
  crmFolder: 'Папка',
  crmFolderNone: 'Без папки',
  crmFolderCustom: 'Новая папка',
  crmTour: 'Тур',
  crmDate: 'Дата выезда',
  crmComment: 'Комментарий',
  crmPauseReason: 'Почему ждём / отказ',
  crmNextStep: 'Следующий шаг',
  crmNextStepAt: 'Когда',
  crmPaid: 'Оплата внесена',
  crmDoubts: 'Сомневается',
  crmStatus: 'Статус',
  crmDeals: 'Попытки записи',
  crmAddDeal: 'Ещё тур',
  crmCalled: 'Позвонил',
  crmWrote: 'Написал',
  crmOpenChat: 'Написать',
  crmCall: 'Позвонить',
  crmSavePerson: 'Сохранить карточку',
  crmBackToList: 'К списку',
  crmError: 'Не удалось сохранить заявку',
  crmConflict: 'Список обновили в другом окне. Обновите страницу.',
  crmMessengers: {
    telegram: 'Telegram',
    whatsapp: 'WhatsApp',
    max: 'Max',
    phone: 'Телефон',
  },
  crmStatuses: {
    new: 'Новая',
    in_progress: 'В работе',
    booked: 'Записали',
    declined: 'Отказ',
    no_answer: 'Нет ответа',
  },
  crmFolders: {
    suppliers: 'Поставщики',
    tour_bases: 'Турбазы',
    captains: 'Капитаны',
    drivers: 'Водители',
    other: 'Другое',
  },
  seasons: {
    winter: 'Зима',
    spring: 'Весна',
    summer: 'Лето',
    fall: 'Осень',
  },
  iconLabels: {
    bed: 'Ночёвка',
    binoculars: 'Наблюдение',
    'book-open': 'Программа',
    'chalkboard-user': 'Инструктаж',
    check: 'Включено',
    dog: 'Собаки',
    heart: 'Забота',
    'helmet-safety': 'Снаряжение',
    'hot-tub-person': 'Баня',
    'mug-hot': 'Горячее питьё',
    'mug-saucer': 'Кофе',
    paw: 'Животные',
    'person-hiking': 'Поход',
    'person-snowboarding': 'Сноуборд',
    plane: 'Перелёт',
    socks: 'Гамаши',
    ticket: 'Билет',
    truck: 'Транспорт',
    'user-tie': 'Гид',
    utensils: 'Еда',
    'van-shuttle': 'Трансфер',
    water: 'Вода',
    wind: 'Ветер',
  } as Record<string, string>,
} as const;
