export interface LegacyRedirectRule {
  from: string;
  to: string;
}

const assertPath = (value: string, label: string): void => {
  if (!value.startsWith('/') || /[\s\r\n]/.test(value)) {
    throw new Error(`Invalid ${label} redirect path: ${value}`);
  }
};

/** Render exact Caddy rules for legacy tour URLs. These are real HTTP 301s. */
export const renderLegacyRedirectRules = (rules: readonly LegacyRedirectRule[]): string => {
  const lines = ['# Generated by npm run og:shells. Do not edit manually.'];
  for (const rule of rules) {
    assertPath(rule.from, 'source');
    assertPath(rule.to, 'target');
    if (rule.from === rule.to) {
      throw new Error(`Legacy redirect points to itself: ${rule.from}`);
    }
    lines.push(`redir ${rule.from} ${rule.to} 301`);
  }
  return `${lines.join('\n')}\n`;
};
