import { describe, expect, it } from 'vitest';
import { renderLegacyRedirectRules } from './renderLegacyRedirectRules';

describe('renderLegacyRedirectRules', () => {
  it('renders exact HTTP 301 rules', () => {
    expect(
      renderLegacyRedirectRules([
        { from: '/tours/summer/summer-10', to: '/tours/summer/robinzonada-v-rayone-tryokhi' },
      ]),
    ).toBe(
      '# Generated by npm run og:shells. Do not edit manually.\n' +
        'redir /tours/summer/summer-10 /tours/summer/robinzonada-v-rayone-tryokhi 301\n',
    );
  });

  it('rejects a self redirect', () => {
    expect(() => renderLegacyRedirectRules([{ from: '/old', to: '/old' }])).toThrow(
      'Legacy redirect points to itself',
    );
  });
});
