import { useEffect, useState } from 'react';
import { adminGetSiteContent, adminPublishSiteContent, adminSaveSiteContent } from './api';
import AdminAlert from './components/AdminAlert';
import AdminButton from './components/AdminButton';
import { AdminFieldLabel, AdminTextArea, AdminTextInput } from './components/AdminFields';
import AdminPageFrame from './components/AdminPageFrame';
import AdminPageHeader from './components/AdminPageHeader';
import AdminStatus from './components/AdminStatus';
import { ADMIN_UI } from './constants/ui';
import type { ContactsContentDocument, FooterContentDocument, FooterContentRow, SiteContentDocument, TeamContentDocument } from '../cms/siteContentDocument';

type Kind = 'team' | 'contacts' | 'footer';
const tabs: Array<{ id: Kind; label: string }> = [
  { id: 'team', label: 'Команда' }, { id: 'contacts', label: 'Контакты' }, { id: 'footer', label: 'Подвал' },
];

const move = <T extends { order: number }>(items: T[], index: number, delta: number) => {
  const next = [...items]; const target = index + delta;
  if (target < 0 || target >= next.length) return next;
  [next[index], next[target]] = [next[target], next[index]];
  return next.map((item, order) => ({ ...item, order }));
};

const TeamTab = ({ value, onChange }: { value: TeamContentDocument; onChange: (value: TeamContentDocument) => void }) => (
  <section className="flex flex-col gap-4" aria-label="Команда">
    <div className="flex flex-wrap items-center justify-between gap-2"><h2 className="text-lg font-semibold">Участники команды</h2><AdminButton onClick={() => onChange({ ...value, members: [...value.members, { id: `member-${Date.now()}`, name: 'Новый участник', photo: { assetId: '', url: '', mimeType: 'image/*', alt: '' }, role: '', roleVisible: true, experience: '', experienceVisible: false, bio: '', bioVisible: true, visible: true, order: value.members.length }] })}>Добавить участника</AdminButton></div>
    {value.members.sort((a, b) => a.order - b.order).map((member, index) => <article key={member.id} className="admin-card flex flex-col gap-3 p-4">
      <div className="flex flex-wrap items-center justify-between gap-2"><strong>{member.name || 'Без имени'}</strong><div className="flex gap-1"><AdminButton variant="ghost" aria-label="Поднять" onClick={() => onChange({ ...value, members: move(value.members, index, -1) })}>↑</AdminButton><AdminButton variant="ghost" aria-label="Опустить" onClick={() => onChange({ ...value, members: move(value.members, index, 1) })}>↓</AdminButton><AdminButton variant="destructive" onClick={() => onChange({ ...value, members: value.members.filter((item) => item.id !== member.id).map((item, order) => ({ ...item, order })) })}>Удалить</AdminButton></div></div>
      <div className="grid gap-3 md:grid-cols-2"><label><AdminFieldLabel htmlFor={`${member.id}-name`} required>Имя</AdminFieldLabel><AdminTextInput id={`${member.id}-name`} value={member.name} onChange={(event) => onChange({ ...value, members: value.members.map((item) => item.id === member.id ? { ...item, name: event.target.value } : item) })} /></label><label><AdminFieldLabel htmlFor={`${member.id}-photo`} required>URL фотографии</AdminFieldLabel><AdminTextInput id={`${member.id}-photo`} value={member.photo.url} onChange={(event) => onChange({ ...value, members: value.members.map((item) => item.id === member.id ? { ...item, photo: { ...item.photo, url: event.target.value } } : item) })} /></label><label><AdminFieldLabel htmlFor={`${member.id}-role`}>Должность</AdminFieldLabel><AdminTextInput id={`${member.id}-role`} value={member.role} onChange={(event) => onChange({ ...value, members: value.members.map((item) => item.id === member.id ? { ...item, role: event.target.value } : item) })} /></label><label><AdminFieldLabel htmlFor={`${member.id}-experience`}>Опыт</AdminFieldLabel><AdminTextInput id={`${member.id}-experience`} value={member.experience} onChange={(event) => onChange({ ...value, members: value.members.map((item) => item.id === member.id ? { ...item, experience: event.target.value } : item) })} /></label></div>
      <label><AdminFieldLabel htmlFor={`${member.id}-bio`}>Описание</AdminFieldLabel><AdminTextArea id={`${member.id}-bio`} rows={3} value={member.bio} onChange={(event) => onChange({ ...value, members: value.members.map((item) => item.id === member.id ? { ...item, bio: event.target.value } : item) })} /></label>
      <div className="flex flex-wrap gap-4 text-sm"><label><input type="checkbox" checked={member.visible} onChange={(event) => onChange({ ...value, members: value.members.map((item) => item.id === member.id ? { ...item, visible: event.target.checked } : item) })} /> Показывать участника</label><label><input type="checkbox" checked={member.roleVisible} onChange={(event) => onChange({ ...value, members: value.members.map((item) => item.id === member.id ? { ...item, roleVisible: event.target.checked } : item) })} /> Показывать должность</label><label><input type="checkbox" checked={member.experienceVisible} onChange={(event) => onChange({ ...value, members: value.members.map((item) => item.id === member.id ? { ...item, experienceVisible: event.target.checked } : item) })} /> Показывать опыт</label><label><input type="checkbox" checked={member.bioVisible} onChange={(event) => onChange({ ...value, members: value.members.map((item) => item.id === member.id ? { ...item, bioVisible: event.target.checked } : item) })} /> Показывать описание</label></div>
    </article>)}
  </section>
);

const ContactsTab = ({ value, onChange }: { value: ContactsContentDocument; onChange: (value: ContactsContentDocument) => void }) => <section className="flex flex-col gap-4"><div className="flex items-center justify-between gap-2"><h2 className="text-lg font-semibold">Контакты</h2><label className="text-sm"><input type="checkbox" checked={value.sectionVisible} onChange={(event) => onChange({ ...value, sectionVisible: event.target.checked })} /> Показывать секцию контактов</label></div><div className="flex flex-col gap-3">{value.channels.sort((a, b) => a.order - b.order).map((channel, index) => <article key={channel.id} className="admin-card grid gap-3 p-4 md:grid-cols-[1fr_1fr_auto]"><label><AdminFieldLabel htmlFor={`${channel.id}-label`}>Название</AdminFieldLabel><AdminTextInput id={`${channel.id}-label`} value={channel.label} onChange={(event) => onChange({ ...value, channels: value.channels.map((item) => item.id === channel.id ? { ...item, label: event.target.value } : item) })} /></label><label><AdminFieldLabel htmlFor={`${channel.id}-href`}>Ссылка или номер</AdminFieldLabel><AdminTextInput id={`${channel.id}-href`} value={channel.href} onChange={(event) => onChange({ ...value, channels: value.channels.map((item) => item.id === channel.id ? { ...item, href: event.target.value } : item) })} /></label><div className="flex items-end gap-1"><AdminButton variant="ghost" onClick={() => onChange({ ...value, channels: move(value.channels, index, -1) })}>↑</AdminButton><AdminButton variant="ghost" onClick={() => onChange({ ...value, channels: move(value.channels, index, 1) })}>↓</AdminButton><label className="flex items-center gap-1 pb-2 text-sm"><input type="checkbox" checked={channel.visible} onChange={(event) => onChange({ ...value, channels: value.channels.map((item) => item.id === channel.id ? { ...item, visible: event.target.checked } : item) })} /> Видим</label></div></article>)}</div><AdminButton variant="secondary" onClick={() => onChange({ ...value, channels: [...value.channels, { id: `channel-${Date.now()}`, label: 'Новая ссылка', href: '#', type: 'link', visible: true, order: value.channels.length }] })}>Добавить ссылку</AdminButton></section>;

const FooterTab = ({ value, onChange }: { value: FooterContentDocument; onChange: (value: FooterContentDocument) => void }) => <section className="flex flex-col gap-4"><h2 className="text-lg font-semibold">Подвал</h2>{value.blocks.sort((a, b) => a.order - b.order).map((block) => <article key={block.id} className="admin-card flex flex-col gap-3 p-4"><label><AdminFieldLabel htmlFor={`${block.id}-heading`}>Заголовок блока</AdminFieldLabel><AdminTextInput id={`${block.id}-heading`} value={block.heading} onChange={(event) => onChange({ ...value, blocks: value.blocks.map((item) => item.id === block.id ? { ...item, heading: event.target.value } : item) })} /></label><label className="text-sm"><input type="checkbox" checked={block.visible} onChange={(event) => onChange({ ...value, blocks: value.blocks.map((item) => item.id === block.id ? { ...item, visible: event.target.checked } : item) })} /> Показывать блок</label>{block.rows.sort((a, b) => a.order - b.order).map((row) => <div key={row.id} className="grid gap-2 border-t border-border-subtle pt-3 md:grid-cols-[1fr_1fr_auto]"><label><AdminFieldLabel htmlFor={`${row.id}-label`}>Строка</AdminFieldLabel><AdminTextInput id={`${row.id}-label`} value={row.label} onChange={(event) => onChange({ ...value, blocks: value.blocks.map((item) => item.id === block.id ? { ...item, rows: item.rows.map((candidate) => candidate.id === row.id ? { ...candidate, label: event.target.value } as FooterContentRow : candidate) } : item) })} /></label><label><AdminFieldLabel htmlFor={`${row.id}-value`}>Значение</AdminFieldLabel><AdminTextInput id={`${row.id}-value`} value={row.value} onChange={(event) => onChange({ ...value, blocks: value.blocks.map((item) => item.id === block.id ? { ...item, rows: item.rows.map((candidate) => candidate.id === row.id ? { ...candidate, value: event.target.value } as FooterContentRow : candidate) } : item) })} /></label><label className="flex items-center gap-1 pb-2 text-sm"><input type="checkbox" checked={row.visible} onChange={(event) => onChange({ ...value, blocks: value.blocks.map((item) => item.id === block.id ? { ...item, rows: item.rows.map((candidate) => candidate.id === row.id ? { ...candidate, visible: event.target.checked } as FooterContentRow : candidate) } : item) })} /> Видим</label></div>)}</article>)}</section>;

const SitePage = () => {
  const [tab, setTab] = useState<Kind>(() => (tabs.some((item) => item.id === location.hash.slice(1)) ? location.hash.slice(1) as Kind : 'team'));
  const [documents, setDocuments] = useState<Partial<Record<Kind, SiteContentDocument>>>({});
  const [revisions, setRevisions] = useState<Partial<Record<Kind, number>>>({});
  const [status, setStatus] = useState<Partial<Record<Kind, string>>>({});
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { let alive = true; void adminGetSiteContent(tab).then((result) => { if (alive) { setDocuments((current) => ({ ...current, [tab]: result.document })); setRevisions((current) => ({ ...current, [tab]: result.meta.rev })); setStatus((current) => ({ ...current, [tab]: 'saved' })); } }).catch((reason: unknown) => { if (alive) { setError(reason instanceof Error ? reason.message : 'site_content_load_failed'); setStatus((current) => ({ ...current, [tab]: 'error' })); } }); return () => { alive = false; }; }, [tab]);
  const document = documents[tab];
  const setDocument = (next: SiteContentDocument) => { setDocuments((current) => ({ ...current, [tab]: next })); setStatus((current) => ({ ...current, [tab]: 'dirty' })); };
  const save = async (publish = false) => { if (document == null || revisions[tab] == null) return; setStatus((current) => ({ ...current, [tab]: 'saving' })); try { const result = publish ? await adminPublishSiteContent(tab, revisions[tab]) : await adminSaveSiteContent(tab, revisions[tab], document); setDocuments((current) => ({ ...current, [tab]: result.document })); setRevisions((current) => ({ ...current, [tab]: result.meta.rev })); setStatus((current) => ({ ...current, [tab]: publish ? 'published' : 'saved' })); setError(null); } catch (reason: unknown) { setError(reason instanceof Error ? reason.message : 'site_content_save_failed'); setStatus((current) => ({ ...current, [tab]: 'error' })); } };
  const content = document == null ? <p className="text-text-muted">{ADMIN_UI.loading}</p> : tab === 'team' ? <TeamTab value={document as TeamContentDocument} onChange={setDocument} /> : tab === 'contacts' ? <ContactsTab value={document as ContactsContentDocument} onChange={setDocument} /> : <FooterTab value={document as FooterContentDocument} onChange={setDocument} />;
  return <AdminPageFrame variant="wide"><AdminPageHeader title={ADMIN_UI.siteNav} description={ADMIN_UI.siteDescription} action={<div className="flex gap-2"><AdminButton variant="secondary" disabled={document == null || status[tab] === 'saving'} onClick={() => void save()}>{status[tab] === 'saving' ? ADMIN_UI.saving : ADMIN_UI.save}</AdminButton><AdminButton disabled={document == null || status[tab] === 'saving'} onClick={() => void save(true)}>Опубликовать</AdminButton></div>} /><div role="tablist" aria-label="Разделы сайта" className="flex flex-wrap gap-2 border-b border-border-subtle"><button className={`admin-tab ${tab === 'team' ? 'admin-tab-active' : ''}`} role="tab" aria-selected={tab === 'team'} onClick={() => { setTab('team'); location.hash = 'team'; }}>Команда</button><button className={`admin-tab ${tab === 'contacts' ? 'admin-tab-active' : ''}`} role="tab" aria-selected={tab === 'contacts'} onClick={() => { setTab('contacts'); location.hash = 'contacts'; }}>Контакты</button><button className={`admin-tab ${tab === 'footer' ? 'admin-tab-active' : ''}`} role="tab" aria-selected={tab === 'footer'} onClick={() => { setTab('footer'); location.hash = 'footer'; }}>Подвал</button></div>{error != null ? <AdminAlert tone="danger">{error}</AdminAlert> : null}<AdminStatus level="secondary">{status[tab] === 'published' ? 'Опубликовано' : status[tab] === 'dirty' ? ADMIN_UI.unpublishedChanges : status[tab] === 'saved' ? ADMIN_UI.saved : ''}</AdminStatus>{content}</AdminPageFrame>;
};

export default SitePage;
