import { useEffect, useState, type KeyboardEvent } from 'react';
import { ChevronDown, ChevronUp, ContactRound, PanelBottom, UsersRound } from 'lucide-react';
import { adminGetSiteContent, adminPublishSiteContent, adminSaveSiteContent, adminUploadSiteAsset } from './api';
import AdminAlert from './components/AdminAlert';
import AdminButton from './components/AdminButton';
import { AdminFieldLabel, AdminTextArea, AdminTextInput } from './components/AdminFields';
import AdminPageFrame from './components/AdminPageFrame';
import AdminPageHeader from './components/AdminPageHeader';
import AdminStatus from './components/AdminStatus';
import { ADMIN_UI } from './constants/ui';
import type { ContactsContentDocument, FooterContentDocument, FooterContentRow, SiteContentDocument, TeamContentDocument } from '../cms/siteContentDocument';

type Kind = 'team' | 'contacts' | 'footer';
const tabs: Array<{ id: Kind; label: string; icon: typeof UsersRound }> = [
  { id: 'team', label: 'Команда', icon: UsersRound },
  { id: 'contacts', label: 'Контакты', icon: ContactRound },
  { id: 'footer', label: 'Подвал', icon: PanelBottom },
];

const move = <T extends { order: number }>(items: T[], index: number, delta: number) => {
  const next = [...items]; const target = index + delta;
  if (target < 0 || target >= next.length) return next;
  [next[index], next[target]] = [next[target], next[index]];
  return next.map((item, order) => ({ ...item, order }));
};

const TeamTab = ({ value, onChange, onUpload }: { value: TeamContentDocument; onChange: (value: TeamContentDocument) => void; onUpload: (memberId: string, file: File) => Promise<void> }) => {
  const members = [...value.members].sort((a, b) => a.order - b.order);
  return (
  <section id="admin-panel-team" role="tabpanel" aria-labelledby="admin-tab-team" className="flex flex-col gap-4">
    <div className="flex flex-wrap items-center justify-between gap-2"><div><h2 className="text-lg font-semibold">Участники команды</h2><p className="mt-1 text-sm text-text-muted">Карточки, порядок и видимость людей на сайте.</p></div><AdminButton onClick={() => onChange({ ...value, members: [...value.members, { id: `member-${Date.now()}`, name: 'Новый участник', photo: { assetId: '', url: '', mimeType: 'image/*', alt: '' }, role: '', roleVisible: true, experience: '', experienceVisible: false, bio: '', bioVisible: true, visible: true, order: value.members.length }] })}>Добавить участника</AdminButton></div>
    <div className="grid gap-3 xl:grid-cols-2">
    {members.map((member, index) => <article key={member.id} className="admin-card flex min-w-0 flex-col gap-3 p-3">
      <div className="flex flex-wrap items-center justify-between gap-2"><strong className="min-w-0 truncate">{member.name || 'Без имени'}</strong><div className="flex gap-1"><AdminButton variant="ghost" aria-label={`Поднять ${member.name || 'участника'}`} disabled={index === 0} onClick={() => onChange({ ...value, members: move(members, index, -1) })}><ChevronUp size={18} aria-hidden="true" /></AdminButton><AdminButton variant="ghost" aria-label={`Опустить ${member.name || 'участника'}`} disabled={index === members.length - 1} onClick={() => onChange({ ...value, members: move(members, index, 1) })}><ChevronDown size={18} aria-hidden="true" /></AdminButton><AdminButton variant="destructive" onClick={() => onChange({ ...value, members: members.filter((item) => item.id !== member.id).map((item, order) => ({ ...item, order })) })}>Удалить</AdminButton></div></div>
      <div className="grid min-w-0 gap-3 sm:grid-cols-[minmax(0,1fr)_minmax(0,1.4fr)]"><div className="min-w-0"><label><AdminFieldLabel htmlFor={`${member.id}-name`} required>Имя</AdminFieldLabel><AdminTextInput id={`${member.id}-name`} value={member.name} onChange={(event) => onChange({ ...value, members: value.members.map((item) => item.id === member.id ? { ...item, name: event.target.value } : item) })} /></label><label className="mt-3 block"><AdminFieldLabel htmlFor={`${member.id}-photo`} required>URL фотографии</AdminFieldLabel><AdminTextInput id={`${member.id}-photo`} value={member.photo.url} onChange={(event) => onChange({ ...value, members: value.members.map((item) => item.id === member.id ? { ...item, photo: { ...item.photo, url: event.target.value } } : item) })} /><input className="mt-2 block max-w-full text-sm" type="file" accept="image/jpeg,image/png,image/webp,image/svg+xml" aria-label={`Загрузить фото для ${member.name || 'участника'}`} onChange={(event) => { const file = event.target.files?.[0]; if (file) void onUpload(member.id, file); }} /></label></div><div className="grid min-w-0 gap-3 sm:grid-cols-2"><label><AdminFieldLabel htmlFor={`${member.id}-role`}>Должность</AdminFieldLabel><AdminTextInput id={`${member.id}-role`} value={member.role} onChange={(event) => onChange({ ...value, members: value.members.map((item) => item.id === member.id ? { ...item, role: event.target.value } : item) })} /></label><label><AdminFieldLabel htmlFor={`${member.id}-experience`}>Опыт</AdminFieldLabel><AdminTextInput id={`${member.id}-experience`} value={member.experience} onChange={(event) => onChange({ ...value, members: value.members.map((item) => item.id === member.id ? { ...item, experience: event.target.value } : item) })} /></label><label className="sm:col-span-2"><AdminFieldLabel htmlFor={`${member.id}-bio`}>Описание</AdminFieldLabel><AdminTextArea id={`${member.id}-bio`} rows={3} value={member.bio} onChange={(event) => onChange({ ...value, members: value.members.map((item) => item.id === member.id ? { ...item, bio: event.target.value } : item) })} /></label></div></div>
      <div className="grid gap-x-4 gap-y-2 border-t border-border-subtle pt-3 text-sm sm:grid-cols-2"><label><input type="checkbox" checked={member.visible} onChange={(event) => onChange({ ...value, members: value.members.map((item) => item.id === member.id ? { ...item, visible: event.target.checked } : item) })} /> Показывать участника</label><label><input type="checkbox" checked={member.roleVisible} onChange={(event) => onChange({ ...value, members: value.members.map((item) => item.id === member.id ? { ...item, roleVisible: event.target.checked } : item) })} /> Показывать должность</label><label><input type="checkbox" checked={member.experienceVisible} onChange={(event) => onChange({ ...value, members: value.members.map((item) => item.id === member.id ? { ...item, experienceVisible: event.target.checked } : item) })} /> Показывать опыт</label><label><input type="checkbox" checked={member.bioVisible} onChange={(event) => onChange({ ...value, members: value.members.map((item) => item.id === member.id ? { ...item, bioVisible: event.target.checked } : item) })} /> Показывать описание</label></div>
    </article>)}
    </div>
  </section>
  );
};

const ContactsTab = ({ value, onChange }: { value: ContactsContentDocument; onChange: (value: ContactsContentDocument) => void }) => { const channels = [...value.channels].sort((a, b) => a.order - b.order); return <section id="admin-panel-contacts" role="tabpanel" aria-labelledby="admin-tab-contacts" className="flex max-w-5xl flex-col gap-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><h2 className="text-lg font-semibold">Контакты</h2><p className="mt-1 text-sm text-text-muted">Ссылки и номера, которые видит посетитель.</p></div><label className="text-sm"><input type="checkbox" checked={value.sectionVisible} onChange={(event) => onChange({ ...value, sectionVisible: event.target.checked })} /> Показывать секцию контактов</label></div><div className="flex max-w-4xl flex-col gap-3">{channels.map((channel, index) => <article key={channel.id} className="admin-card grid min-w-0 gap-3 p-3 md:grid-cols-[minmax(0,1fr)_minmax(0,1.5fr)_auto]"><label><AdminFieldLabel htmlFor={`${channel.id}-label`}>Название</AdminFieldLabel><AdminTextInput id={`${channel.id}-label`} value={channel.label} onChange={(event) => onChange({ ...value, channels: value.channels.map((item) => item.id === channel.id ? { ...item, label: event.target.value } : item) })} /></label><label><AdminFieldLabel htmlFor={`${channel.id}-href`}>Ссылка или номер</AdminFieldLabel><AdminTextInput id={`${channel.id}-href`} value={channel.href} onChange={(event) => onChange({ ...value, channels: value.channels.map((item) => item.id === channel.id ? { ...item, href: event.target.value } : item) })} /></label><div className="flex items-end gap-1"><AdminButton variant="ghost" aria-label={`Поднять ${channel.label}`} disabled={index === 0} onClick={() => onChange({ ...value, channels: move(channels, index, -1) })}><ChevronUp size={18} aria-hidden="true" /></AdminButton><AdminButton variant="ghost" aria-label={`Опустить ${channel.label}`} disabled={index === channels.length - 1} onClick={() => onChange({ ...value, channels: move(channels, index, 1) })}><ChevronDown size={18} aria-hidden="true" /></AdminButton><label className="flex items-center gap-1 pb-2 text-sm"><input type="checkbox" checked={channel.visible} onChange={(event) => onChange({ ...value, channels: value.channels.map((item) => item.id === channel.id ? { ...item, visible: event.target.checked } : item) })} /> Видим</label></div></article>)}</div><AdminButton variant="secondary" className="w-fit" onClick={() => onChange({ ...value, channels: [...value.channels, { id: `channel-${Date.now()}`, label: 'Новая ссылка', href: '#', type: 'link', visible: true, order: value.channels.length }] })}>Добавить ссылку</AdminButton></section>; };

const FooterTab = ({ value, onChange }: { value: FooterContentDocument; onChange: (value: FooterContentDocument) => void }) => <section id="admin-panel-footer" role="tabpanel" aria-labelledby="admin-tab-footer" className="flex max-w-5xl flex-col gap-4"><div><h2 className="text-lg font-semibold">Подвал</h2><p className="mt-1 text-sm text-text-muted">Ссылки и информационные блоки внизу сайта.</p></div>{[...value.blocks].sort((a, b) => a.order - b.order).map((block) => <article key={block.id} className="admin-card flex max-w-4xl flex-col gap-3 p-3"><div className="grid gap-3 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-end"><label><AdminFieldLabel htmlFor={`${block.id}-heading`}>Заголовок блока</AdminFieldLabel><AdminTextInput id={`${block.id}-heading`} value={block.heading} onChange={(event) => onChange({ ...value, blocks: value.blocks.map((item) => item.id === block.id ? { ...item, heading: event.target.value } : item) })} /></label><label className="pb-2 text-sm"><input type="checkbox" checked={block.visible} onChange={(event) => onChange({ ...value, blocks: value.blocks.map((item) => item.id === block.id ? { ...item, visible: event.target.checked } : item) })} /> Показывать блок</label></div>{[...block.rows].sort((a, b) => a.order - b.order).map((row) => <div key={row.id} className="grid gap-2 border-t border-border-subtle pt-3 md:grid-cols-[minmax(0,1fr)_minmax(0,1.5fr)_auto]"><label><AdminFieldLabel htmlFor={`${row.id}-label`}>Строка</AdminFieldLabel><AdminTextInput id={`${row.id}-label`} value={row.label} onChange={(event) => onChange({ ...value, blocks: value.blocks.map((item) => item.id === block.id ? { ...item, rows: item.rows.map((candidate) => candidate.id === row.id ? { ...candidate, label: event.target.value } as FooterContentRow : candidate) } : item) })} /></label><label><AdminFieldLabel htmlFor={`${row.id}-value`}>Значение</AdminFieldLabel><AdminTextInput id={`${row.id}-value`} value={row.value} onChange={(event) => onChange({ ...value, blocks: value.blocks.map((item) => item.id === block.id ? { ...item, rows: item.rows.map((candidate) => candidate.id === row.id ? { ...candidate, value: event.target.value } as FooterContentRow : candidate) } : item) })} /></label><label className="flex items-center gap-1 pb-2 text-sm"><input type="checkbox" checked={row.visible} onChange={(event) => onChange({ ...value, blocks: value.blocks.map((item) => item.id === block.id ? { ...item, rows: item.rows.map((candidate) => candidate.id === row.id ? { ...candidate, visible: event.target.checked } as FooterContentRow : candidate) } : item) })} /> Видим</label></div>)}</article>)}</section>;

const SitePage = () => {
  const [tab, setTab] = useState<Kind>(() => (tabs.some((item) => item.id === location.hash.slice(1)) ? location.hash.slice(1) as Kind : 'team'));
  const [documents, setDocuments] = useState<Partial<Record<Kind, SiteContentDocument>>>({});
  const [revisions, setRevisions] = useState<Partial<Record<Kind, number>>>({});
  const [status, setStatus] = useState<Partial<Record<Kind, string>>>({});
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { let alive = true; void adminGetSiteContent(tab).then((result) => { if (alive) { setDocuments((current) => ({ ...current, [tab]: result.document })); setRevisions((current) => ({ ...current, [tab]: result.meta.rev })); setStatus((current) => ({ ...current, [tab]: 'saved' })); } }).catch((reason: unknown) => { if (alive) { setError(reason instanceof Error ? reason.message : 'site_content_load_failed'); setStatus((current) => ({ ...current, [tab]: 'error' })); } }); return () => { alive = false; }; }, [tab]);
  const document = documents[tab];
  const setDocument = (next: SiteContentDocument) => { setDocuments((current) => ({ ...current, [tab]: next })); setStatus((current) => ({ ...current, [tab]: 'dirty' })); };
  const uploadTeamPhoto = async (memberId: string, file: File) => { try { const result = await adminUploadSiteAsset('team', file); const team = documents.team; if (team?.kind === 'team') setDocument({ ...team, members: team.members.map((member) => member.id === memberId ? { ...member, photo: result.asset } : member) }); } catch (reason: unknown) { setError(reason instanceof Error ? reason.message : 'site_asset_upload_failed'); } };
  const save = async (publish = false) => { if (document == null || revisions[tab] == null) return; setStatus((current) => ({ ...current, [tab]: 'saving' })); try { const result = publish ? await adminPublishSiteContent(tab, revisions[tab]) : await adminSaveSiteContent(tab, revisions[tab], document); setDocuments((current) => ({ ...current, [tab]: result.document })); setRevisions((current) => ({ ...current, [tab]: result.meta.rev })); setStatus((current) => ({ ...current, [tab]: publish ? 'published' : 'saved' })); setError(null); } catch (reason: unknown) { setError(reason instanceof Error ? reason.message : 'site_content_save_failed'); setStatus((current) => ({ ...current, [tab]: 'error' })); } };
  const content = document == null ? <p className="text-text-muted">{ADMIN_UI.loading}</p> : tab === 'team' ? <TeamTab value={document as TeamContentDocument} onChange={setDocument} onUpload={uploadTeamPhoto} /> : tab === 'contacts' ? <ContactsTab value={document as ContactsContentDocument} onChange={setDocument} /> : <FooterTab value={document as FooterContentDocument} onChange={setDocument} />;
  const selectTab = (next: Kind) => { setTab(next); setError(null); };
  const onTabKeyDown = (event: KeyboardEvent<HTMLDivElement>) => { const index = tabs.findIndex((item) => item.id === tab); const delta = event.key === 'ArrowRight' ? 1 : event.key === 'ArrowLeft' ? -1 : event.key === 'Home' ? 0 : event.key === 'End' ? tabs.length - 1 : null; if (delta == null) return; event.preventDefault(); selectTab(tabs[(delta === 0 || delta === tabs.length - 1) ? delta : (index + delta + tabs.length) % tabs.length].id); };
  return <AdminPageFrame variant="wide"><AdminPageHeader title={ADMIN_UI.siteNav} description={ADMIN_UI.siteDescription} action={<div className="flex gap-2"><AdminButton variant="secondary" disabled={document == null || status[tab] === 'saving'} onClick={() => void save()}>{status[tab] === 'saving' ? ADMIN_UI.saving : ADMIN_UI.save}</AdminButton><AdminButton disabled={document == null || status[tab] === 'saving'} onClick={() => void save(true)}>Опубликовать</AdminButton></div>} /><div role="tablist" aria-label="Разделы сайта" onKeyDown={onTabKeyDown} className="grid max-w-3xl grid-cols-3 gap-1 rounded-admin-control border border-divider bg-surface-light p-1"><div className="contents">{tabs.map(({ id, label, icon: Icon }) => <button key={id} type="button" id={`admin-tab-${id}`} role="tab" aria-selected={tab === id} aria-controls={`admin-panel-${id}`} tabIndex={tab === id ? 0 : -1} className={`inline-flex min-h-11 items-center justify-center gap-2 rounded-admin-control px-2 text-sm transition-colors motion-reduce:transition-none ${tab === id ? 'admin-nav-active' : 'admin-nav-item'}`} onClick={() => selectTab(id)}><Icon size={17} aria-hidden="true" /><span>{label}</span></button>)}</div></div>{error != null ? <AdminAlert tone="danger">{error}</AdminAlert> : null}<AdminStatus level="secondary">{status[tab] === 'published' ? 'Опубликовано' : status[tab] === 'dirty' ? ADMIN_UI.unpublishedChanges : status[tab] === 'saved' ? ADMIN_UI.saved : ''}</AdminStatus>{content}</AdminPageFrame>;
};

export default SitePage;
